### ISSUE TITLE
remove time from Level 3

### ISSUE THREAD

**Issue by hgloeckner** [atmdrops/pydropsonde#16]
Maybe we can the 'interpolated time' dimension from level 3. it does not have much meaning anyway

**Comment by Geet-George** [comment]
I agree that it doesn't have any physical meaning, but it does indicate the "mean time" for when the bin was sampled. Having time information there, I think, might be quite useful in some cases. An example off the top of my head would be when we tried to get sounding value closest to the clouds we got from SpecMACS images.
