### ISSUE TITLE
Run pipeline section for each sonde before changing to the next

### ISSUE THREAD

**Issue by hgloeckner** [atmdrops/pydropsonde#21]
Maybe it would be nice to run the pipeline sections per sonde together and then switch to the next sonde instead of running each step on each sonde (like this, if one step fails for one of them somewhere in the l2->l3 processing all other calculations are "wasted"
but maybe we just need to improve our error catch

**Comment by d70-t** [comment]
Maybe super not helpful, but probably interesting: This sounds like the classic example of an application of the [Haskell Rewrite Rules](https://downloads.haskell.org/~ghc/6.12.2/docs/html/users_guide/rewrite-rules.html). I.e.:

```
"map/map"    forall f g xs.  map f (map g xs) = map (f.g) xs
```
which means: No matter which functions `f` and `g` you have, whenever you first loop over a List of `xs` and apply `g` to each element (i.e. run the `map` function), then have another loop applying `f` to each resulting element, you could just as well to a single loop and apply `g` and then `f` together on each element.

The GHC Haskell compiler will by default do that optimization whenever it sees the double-loop pattern.

For the wasted-ness of the computation, you'd probably still want to have some mechanism of catching errors, while the processing keeps going. If the errors aren't caught and handled, the program will always end in a somewhat ill-defined state, so matter if looping is done in the one or other way.

In a way, you could think of the individual step functions as a function from a certain type `A` (e.g. Sonde) to one of three outcomes:
* `A` (e.g. another Sonde)
* `None` (signifying something went wrong, without further specification)
* raises an Exception (also signigying something went wrong, but carrying some information about what went wrong)

In that sense, it might be useful to treat Exceptions more like the `None` case (which continues processing in a defined way), but maybe making sure that some kind of logging or reporting is triggered which surfaces the information about what went wrong to the user.

**Comment by hgloeckner** [comment]
probably, we should leave it as it is and add error-catch as they arise :)
