### ISSUE TITLE
Decide whether we want M and n values

### ISSUE THREAD

**Issue by hgloeckner** [atmdrops/pydropsonde#32]
The M and n in [Joanne](https://github.com/Geet-George/JOANNE/blob/master/joanne/Level_3/fn_3.py) are basically numbers that tell how many points are in each interpolation bin.  
Maybe we should decide whether we need those? (or if they are more like a meta-data-dataset)?

**Comment by ninarobbins** [comment]
Maybe it would be good to keep it in case someone finds it useful for statistics? I'm not sure how these would be used, but I'd tend to keep things that were also in JOANNE rather than removing

**Comment by ninarobbins** [comment]
We could make these ancillary variables, not sure if they are already so

**Comment by hgloeckner** [comment]
> We could make these ancillary variables, not sure if they are already so

that's a good idea. Does standard xarray have this functionality? I found it in [cf_xarray](https://cf-xarray.readthedocs.io/en/latest/examples/introduction.html) but not in the normal xarray (maybe you can provide a link? I haven't worked with that functionality before)

**Comment by d70-t** [comment]
CF conventions [define some attributes, which can be used to describe a variable as being ancillary to other variables](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.11/cf-conventions.html#ancillary-data).
I guess it's a good idea to add those attributes if applicable. Later on people or libraries can use those attributes to better understand the dataset.

**Comment by hgloeckner** [comment]
> CF conventions [define some attributes, which can be used to describe a variable as being ancillary to other variables](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.11/cf-conventions.html#ancillary-data). I guess it's a good idea to add those attributes if applicable. Later on people or libraries can use those attributes to better understand the dataset.

those are really cool. we can also flag all the quality control variables. Thanks!

**Comment by Geet-George** [comment]
The M and n are indeed metadata about how the data was produced. These are recommended by CF conventions (e.g. [this link](https://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/build/ch07s03.html), although the ship internet does not allow me to see it so it might not be the right link). I think it is a nice measure for the user to decide on the reliability of that interpolated data, and would recommend keeping them, especially with that idea of keeping them as ancillary variables.
