### ISSUE TITLE
Add fallspeed

### ISSUE THREAD

**Issue by hgloeckner** [atmdrops/pydropsonde#40]
time is weird after level 2 so fallspeed could be added to level 3

**Comment by ninarobbins** [comment]
Would this be in altitude or pressure space? is there any issue with the interpolated grid on L3?

**Comment by hgloeckner** [comment]
sorry, I only saw this now. 

There is no issue with the interpolation, I think, but nevertheless for speed calculation interpolated time is a bad dimension, because we do the interpolation with bins. That is why fallspeed should be calculated on level 2 and not on the interpolated grid. Theoretically, we could calculate both, but I think I'd just stick with altitude first.

**Comment by hgloeckner** [comment]
I think, we can leave this, as it was requested to have a dataset that has as few derived variables as possible (e.g. Issue #64). We might consider adding this to a potential Sonata dataset, but it's not an issue for the general package
