### ISSUE TITLE
Change default QC behaviour?

### ISSUE THREAD

**Issue by Geet-George** [atmdrops/pydropsonde#66]
Currently, the QC filtering (`filter_qc_flags`) does not remove any sondes. [This commit](https://github.com/atmdrops/pydropsonde/commit/40c6b5aa5fc3c1e88bf3913552502c298894fa98) is the culprit! The default behaviour was changed to accommodate (AC)3 strategy, where they didn't want to filter any sonde, but add quality flags instead. 

I would recommend going for the JOANNE strategy, i.e. only keeping `GOOD` (implementation remaining) sondes post-L1. If any other sondes are needed, then the user can dig them out of L1, but as data providers we can keep the quality and definitions consistent if we have only good sondes. 

So, if we agree on this recommendation, then we should basically undo [the aforementioned commit](https://github.com/atmdrops/pydropsonde/commit/40c6b5aa5fc3c1e88bf3913552502c298894fa98) and it should work okay. :)

**Comment by hgloeckner** [comment]
I think it's okay to have that as the default, but I added a description of the dangers to the docs with PR #67 and also added the qc to the example config. Hopefully that's enough?

**Comment by Geet-George** [comment]
Yep, I think that should be enough. Thanks Helene.
