### ISSUE TITLE
l3 file with all flights

### ISSUE THREAD

**Issue by hgloeckner** [atmdrops/pydropsonde#9]
Right now if the routine is run over all flights, all of them are concatenates all of the sondes from all flights to one file and saves it to the first flight directory. 

This could be either fixed by making on L3 file for each flight or moving it out of the directory structure. 
Maybe the first solution is better? 

Any opinions? @Geet-George @tmieslinger @ninarobbins

**Comment by Geet-George** [comment]
Hey @hgloeckner, I think the L3 is most useful if all sondes of a campaign are available together instead of different flights. Why would the latter option mean taking it out of the directory structure? Did we go back to the earlier structure of flights first instead of levels first?

**Comment by hgloeckner** [comment]
okay nice. then it does what it should. 

The thing is that on the dataserver they have a structure like halo/dropsondes/<flight_id>/Level_0 or something like that. but probably we can customize that

**Comment by d70-t** [comment]
The data server layout is up to modifications. I'd consider the current state as a first draft.

Analysis-wise we've learned in the last years, that cutting things apart is easier than glueing them together. So if one can reasonably stitch together a dataset during routine postprocessing, we'd generally prefer that over many individual datasets, as this simplifies things for downstream users. Only if things don't fit together, they should be separate (e.g L0 data certainly shouldn't be merged).

**Comment by Geet-George** [comment]
I'm not sure I understood the problem exactly. In the current structure, L3 can be stored directly as L3.nc in `halo/dropsondes/` or within `halo/dropsondes/Level_3`.

**Comment by hgloeckner** [comment]
> > The thing is that on the dataserver they have a structure like halo/dropsondes/<flight_id>/Level_0 or something like that. but probably we can customize that
> 
> I'm not sure I understood the problem exactly. In the current structure, L3 can be stored directly as `L3.nc` in `halo/dropsondes/` or within `halo/dropsondes/Level_3`.

Yeah, it's possible. The I'd just prefer to not have level-folders on different directory levels. But I realyzed that at the moment we caan just change it to halo/dropsondes/Level_0/... and then we can easily have a halo/dropsonde/Level_3/. 

So that's more or less solved I guess

**Comment by hgloeckner** [comment]
> The data server layout is up to modifications. I'd consider the current state as a first draft.
> 
> Analysis-wise we've learned in the last years, that cutting things apart is easier than glueing them together. So if one can reasonably stitch together a dataset during routine postprocessing, we'd generally prefer that over many individual datasets, as this simplifies things for downstream users. Only if things don't fit together, they should be separate (e.g L0 data certainly shouldn't be merged).

good to know, then we'll definitely have just one Level_3 file.
